## **Introduction to numpy**
Numpy: Numerical  <br>
import numpy as np

In [1]:
import numpy as np

### Creating a array

In [2]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [3]:
type(arr)

numpy.ndarray

### Creating a 2D array

In [5]:
arr2d = np.array([[1,2,3], [4,5,6]])
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(arr2d)

numpy.ndarray

### Shape of array

In [7]:
arr.shape

(6,)

In [8]:
arr2d.shape

(2, 3)

### Creating a special array

### 1. Array of zeros

In [10]:
zero_arr = np.zeros((3,4))
zero_arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 2. Array of ones

In [11]:
ones_arr = np.ones((2,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

### 3. Identity matrix

In [14]:
identity_mat = np.eye(3)
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4. Random array

In [18]:
random_arr = np.random.rand(3,3)
random_arr

array([[0.99081381, 0.65822719, 0.11008774],
       [0.81073021, 0.39556397, 0.1210679 ],
       [0.51488734, 0.78947572, 0.47433096]])

---

### Array indexing and slicing

In [19]:
arr = np.array([10,20,30,40,50])

In [20]:
# First element
arr[0]

10

In [21]:
# last element
arr[-1]

50

In [24]:
arr[1:4]

array([20, 30, 40])

In [25]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr2d[0, 1]

2

In [27]:
arr2d[1,2]

6

### Basic Mathematical operations

In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [29]:
# Addition
arr1 + arr2

array([5, 7, 9])

In [30]:
list1 = [1,2,3]
list2 = [4,5,6]
list1 + list2

[1, 2, 3, 4, 5, 6]

In [32]:
# SUbtraction
arr2 - arr1

array([3, 3, 3])

In [33]:
# Multiplication 
arr1 * arr2

array([ 4, 10, 18])

In [34]:
# Division
arr2 / arr1

array([4. , 2.5, 2. ])

### Universal functions

In [35]:
arr = np.array([1,4,9,16,25])

In [40]:
print("Square root", np.sqrt(arr), "\n")  # square root
print("Exponential", np.exp(arr), "\n")   # exponential
print("Logarithm", np.log(arr), "\n")   # logarithm

Square root [1. 2. 3. 4. 5.] 

Exponential [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10] 

Logarithm [0.         1.38629436 2.19722458 2.77258872 3.21887582] 



### Aggregation function

In [41]:
arr

array([ 1,  4,  9, 16, 25])

In [42]:
print("Sum", np.sum(arr))
print("Mean", np.mean(arr))
print("Min", np.min(arr))
print("Max", np.max(arr))
print("Standard deviation", np.std(arr))

Sum 55
Mean 11.0
Min 1
Max 25
Standard deviation 8.648699324175862


## **Introduction to Pandas**
Series - one dimensional array <br>
DataFrame - Two dimensional labelled array <br>

**import pandas as pd**

In [43]:
import pandas as pd

### Create a Series

In [44]:
data = [10,20,30,40,50]

In [45]:
type(data)

list

In [46]:
series = pd.Series(data)

In [47]:
series

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [48]:
type(series)

pandas.core.series.Series

### Create a data frame

In [49]:
data = {
    "Name" : ["Rahul", "Raj", "Nikhil", "Gauri"],
    "Age" : [25,25,26,24],
    "Company" : ["Antwalk", "Zensar technologies", "Accenture", "Capgemini"],
    "Salary" : [20000,25000,30000,50000]
}

In [50]:
type(data)

dict

In [51]:
df = pd.DataFrame(data)

In [52]:
df

Name  Age              Company  Salary
0   Rahul   25              Antwalk   20000
1     Raj   25  Zensar technologies   25000
2  Nikhil   26            Accenture   30000
3   Gauri   24            Capgemini   50000

### Reading and Writing data

In [53]:
df = pd.read_csv("https://raw.githubusercontent.com/rahulinchal/CSV-Files-/refs/heads/main/Data/Job_Placement_Data.csv")

In [54]:
df.head()

gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
0      M           67.00    Others           91.00    Others    Commerce   
1      M           79.33   Central           78.33    Others     Science   
2      M           65.00   Central           68.00   Central        Arts   
3      M           56.00   Central           52.00   Central     Science   
4      M           85.80   Central           73.60   Central    Commerce   

   degree_percentage undergrad_degree work_experience  emp_test_percentage  \
0              58.00         Sci&Tech              No                 55.0   
1              77.48         Sci&Tech             Yes                 86.5   
2              64.00        Comm&Mgmt              No                 75.0   
3              52.00         Sci&Tech              No                 66.0   
4              73.30        Comm&Mgmt              No                 96.8   

  specialisation  mba_percent      status  
0         Mkt&HR        58.80      Placed  
1        Mkt&Fin        66.28      Placed  
2        Mkt&Fin        57.80      Placed  
3         Mkt&HR        59.43  Not Placed  
4        Mkt&Fin        55.50      Placed

In [55]:
type(df)

pandas.core.frame.DataFrame

In [57]:
df.tail()

gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
210      M            80.6    Others            82.0    Others    Commerce   
211      M            58.0    Others            60.0    Others     Science   
212      M            67.0    Others            67.0    Others    Commerce   
213      F            74.0    Others            66.0    Others    Commerce   
214      M            62.0   Central            58.0    Others     Science   

     degree_percentage undergrad_degree work_experience  emp_test_percentage  \
210               77.6        Comm&Mgmt              No                 91.0   
211               72.0         Sci&Tech              No                 74.0   
212               73.0        Comm&Mgmt             Yes                 59.0   
213               58.0        Comm&Mgmt              No                 70.0   
214               53.0        Comm&Mgmt              No                 89.0   

    specialisation  mba_percent      status  
210        Mkt&Fin        74.49      Placed  
211        Mkt&Fin        53.62      Placed  
212        Mkt&Fin        69.72      Placed  
213         Mkt&HR        60.23      Placed  
214         Mkt&HR        60.22  Not Placed

In [58]:
df.shape

(215, 13)

### Inspecting the data

In [59]:
df.shape

(215, 13)

In [60]:
df.columns

Index(['gender', 'ssc_percentage', 'ssc_board', 'hsc_percentage', 'hsc_board',
       'hsc_subject', 'degree_percentage', 'undergrad_degree',
       'work_experience', 'emp_test_percentage', 'specialisation',
       'mba_percent', 'status'],
      dtype='object')

In [61]:
df.dtypes

gender                  object
ssc_percentage         float64
ssc_board               object
hsc_percentage         float64
hsc_board               object
hsc_subject             object
degree_percentage      float64
undergrad_degree        object
work_experience         object
emp_test_percentage    float64
specialisation          object
mba_percent            float64
status                  object
dtype: object

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               215 non-null    object 
 1   ssc_percentage       215 non-null    float64
 2   ssc_board            215 non-null    object 
 3   hsc_percentage       215 non-null    float64
 4   hsc_board            215 non-null    object 
 5   hsc_subject          215 non-null    object 
 6   degree_percentage    215 non-null    float64
 7   undergrad_degree     215 non-null    object 
 8   work_experience      215 non-null    object 
 9   emp_test_percentage  215 non-null    float64
 10  specialisation       215 non-null    object 
 11  mba_percent          215 non-null    float64
 12  status               215 non-null    object 
dtypes: float64(5), object(8)
memory usage: 22.0+ KB


In [64]:
df.describe().T

count       mean        std    min     25%   50%     75%  \
ssc_percentage       215.0  67.303395  10.827205  40.89  60.600  67.0  75.700   
hsc_percentage       215.0  66.333163  10.897509  37.00  60.900  65.0  73.000   
degree_percentage    215.0  66.370186   7.358743  50.00  61.000  66.0  72.000   
emp_test_percentage  215.0  72.100558  13.275956  50.00  60.000  71.0  83.500   
mba_percent          215.0  62.278186   5.833385  51.21  57.945  62.0  66.255   

                       max  
ssc_percentage       89.40  
hsc_percentage       97.70  
degree_percentage    91.00  
emp_test_percentage  98.00  
mba_percent          77.89

### Selecting the columns and rows

In [65]:
df.head()

gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
0      M           67.00    Others           91.00    Others    Commerce   
1      M           79.33   Central           78.33    Others     Science   
2      M           65.00   Central           68.00   Central        Arts   
3      M           56.00   Central           52.00   Central     Science   
4      M           85.80   Central           73.60   Central    Commerce   

   degree_percentage undergrad_degree work_experience  emp_test_percentage  \
0              58.00         Sci&Tech              No                 55.0   
1              77.48         Sci&Tech             Yes                 86.5   
2              64.00        Comm&Mgmt              No                 75.0   
3              52.00         Sci&Tech              No                 66.0   
4              73.30        Comm&Mgmt              No                 96.8   

  specialisation  mba_percent      status  
0         Mkt&HR        58.80      Placed  
1        Mkt&Fin        66.28      Placed  
2        Mkt&Fin        57.80      Placed  
3         Mkt&HR        59.43  Not Placed  
4        Mkt&Fin        55.50      Placed

In [70]:
df[['work_experience', 'emp_test_percentage']]

work_experience  emp_test_percentage
0                No                 55.0
1               Yes                 86.5
2                No                 75.0
3                No                 66.0
4                No                 96.8
..              ...                  ...
210              No                 91.0
211              No                 74.0
212             Yes                 59.0
213              No                 70.0
214              No                 89.0

[215 rows x 2 columns]

### Filtering data

In [73]:
filt_df = df[df['degree_percentage'] > 60.0]

In [74]:
filt_df

gender  ssc_percentage ssc_board  hsc_percentage hsc_board hsc_subject  \
1        M           79.33   Central           78.33    Others     Science   
2        M           65.00   Central           68.00   Central        Arts   
4        M           85.80   Central           73.60   Central    Commerce   
5        M           55.00    Others           49.80    Others     Science   
6        F           46.00    Others           49.20    Others    Commerce   
..     ...             ...       ...             ...       ...         ...   
208      F           43.00   Central           60.00    Others     Science   
209      M           62.00   Central           72.00   Central    Commerce   
210      M           80.60    Others           82.00    Others    Commerce   
211      M           58.00    Others           60.00    Others     Science   
212      M           67.00    Others           67.00    Others    Commerce   

     degree_percentage undergrad_degree work_experience  emp_test_percentage  \
1                77.48         Sci&Tech             Yes                86.50   
2                64.00        Comm&Mgmt              No                75.00   
4                73.30        Comm&Mgmt              No                96.80   
5                67.25         Sci&Tech             Yes                55.00   
6                79.00        Comm&Mgmt              No                74.28   
..                 ...              ...             ...                  ...   
208              65.00        Comm&Mgmt              No                92.66   
209              65.00        Comm&Mgmt              No                67.00   
210              77.60        Comm&Mgmt              No                91.00   
211              72.00         Sci&Tech              No                74.00   
212              73.00        Comm&Mgmt             Yes                59.00   

    specialisation  mba_percent      status  
1          Mkt&Fin        66.28      Placed  
2          Mkt&Fin        57.80      Placed  
4          Mkt&Fin        55.50      Placed  
5          Mkt&Fin        51.58  Not Placed  
6          Mkt&Fin        53.29  Not Placed  
..             ...          ...         ...  
208         Mkt&HR        62.92  Not Placed  
209        Mkt&Fin        56.49      Placed  
210        Mkt&Fin        74.49      Placed  
211        Mkt&Fin        53.62      Placed  
212        Mkt&Fin        69.72      Placed  

[167 rows x 13 columns]

In [75]:
filt_df.degree_percentage.unique()

array([77.48, 64.  , 73.3 , 67.25, 79.  , 66.  , 72.  , 61.  , 78.3 ,
       65.  , 69.  , 65.6 , 70.  , 85.  , 72.23, 64.74, 78.86, 67.5 ,
       73.  , 66.4 , 81.  , 80.  , 68.  , 68.4 , 61.4 , 74.  , 72.11,
       66.89, 67.4 , 75.  , 67.  , 72.7 , 62.  , 71.  , 78.  , 71.72,
       70.2 , 77.5 , 71.93, 64.5 , 77.2 , 82.  , 76.  , 63.  , 83.  ,
       66.6 , 64.6 , 69.6 , 69.3 , 64.33, 75.5 , 77.72, 77.  , 69.5 ,
       73.43, 70.67, 71.25, 84.  , 60.9 , 77.25, 63.35, 61.26, 64.27,
       64.2 , 62.8 , 64.21, 69.2 , 64.8 , 91.  , 77.6 ])